### PR TITLE
Move `#![deny(missing_docs)]` to the top level

### PR DESCRIPTION
**Pull request by tbu-**
This will catch all missing documentation.

### CODE REVIEW

**Comment by soc** [comment]
Oh, I wasn't aware that having it at the top-level would also apply to all other files, do I understand this correctly?

**Comment by dwijnand** [comment]
yeah, it does because `mod lin;` inlines lin.rs into mod.rs.

I've seen people refer to https://manishearth.github.io/blog/2017/05/14/mentally-modelling-modules/ as how they finally grokked how modules actually work.

**Comment by soc** [comment]
@dwijnand Thanks! I really need to keep reminding me that every crate creates a single artifact in the end, and that stuff like `mod` is modifying what ends up in that final file.

**Comment by soc** [comment]
Thanks @tbu-!

**Pull request merged**
