### PR TITLE
Road to 1.0

### PR DESCRIPTION
**Pull request by soc**
Fixes https://github.com/soc/directories-rs/issues/37.

### CODE REVIEW

**Comment by tbu-** [comment]
I'd suggest you to use `Result<…, Error>` instead of `Option<…>`, where error is something like
```
#[derive(Debug)]
pub struct Error {
    _opaque: (),
}
```

This would allow you to add information to the error cases even after releasing 1.0.

**Comment by soc** [comment]
@tbu- Mhhh, or maybe I should just bite the bullet and figure out all the error cases now.

It would certainly make sense to distinguish between an error because the function is not supported on the given platform, and an error due to some misconfiguration on some individual machine.

Errors I can think of:

- `FunctionNotSupportedOnCurrentPlatform` // e. g. calling `runtime_dir` on Windows
- `InvalidHomeEnvironmentVariable` // can this actually happen? there is always a fallback...
- `MissingUserEntry` // /etc/passwd cannot find user with the current uid
- `EmptyUserEntryHomeField` // /the pw field in /etc/passwd is empty

Anything I'm missing?

**Comment by tbu-** [comment]
> Mhhh, or maybe I should just bite the bullet and figure out all the error cases now.

I think that's never going to work.

I think it's generally accepted practice to make the error type opaque, maybe together with `kind` function returning an `ErrorKind` (with a hidden variant to keep it extendable). Even the standard library goes that way, and it's not the only one.

**Comment by soc** [comment]
@tbu- What's the benefit of using it over `Option` if the errors are hidden anyway? Maybe I misunderstood something here ...

**Comment by tbu-** [comment]
The benefit over `Option` is so it stays extensible into the next step. The benefit of an opaque `Error` struct is that it stays extensible, but you can expose an `ErrorKind` with any number of public variants (*and* a hidden variant, so you can add more variants in the future), so that users can match known errors.

**Comment by tbu-** [comment]
That works. Note that they also added a hidden variant. Also note that this makes existing errors non-extensible, i.e. you can't add extra information to already existing errors.

**Comment by soc** [comment]
Thanks! I'll need to think about it.

**Comment by soc** [comment]
@tbu- Let's do it like this: I'll ship `directories` 1.0 with `Option` so that it is consistent with `dirs` 1.0, keep monitoring the situation and if there is more demand for a better error representation, I'll cut a 2.0 for both `dirs` and `directories`. What do you think?

**Comment by tbu-** [comment]
The good thing about using an opaque error type is that you can add the information without making breaking changes. Users can go back to options by calling `ok()` on the result. The [API guidelines](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-good-err) say that you should have a meaningful error type (not `()`, and `Option<T>` is equivalent to `Result<T, ()>`), so that end users even see a useful error message if the developer decides to `unwrap` the result of a `directories` function.

I don't know. I guess it doesn't matter too much at first. If the crate becomes bigger it might pose a problem, because then everyone depends on version 1 of the library.

**Comment by tbu-** [comment]
Mh...

There seem to be different kinds of functions.

`home_dir` is kind of expected to exist, but if it cannot be determined, it should likely be an error. Maybe `Result<BaseDirs, Error>` as a result of `BaseDirs::new`, `home_dir`  on `BaseDirs` returning just `PathBuf`?

`executable_dir` on the other hand exists only on Linux, it's not really an error that it doesn't exist on Windows. A function `executable_dir` on `BaseDirs` returning `Option<PathBuf>`?

**Comment by soc** [comment]
@tbu- Thanks for your help! I will create a new ticket concerning the `Option`/`Result` question, so that the thoughts around this are not forgotten.

My thought on functions not existing on some platform was that even there it would be helpful to have a `Result` there that clearly spells out that the function is not suported on that platform (vs. some other reasons for failure).

**Pull request merged**
