### PR TITLE
Add benchmarks testing the constructors

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
One of them stands out:

```
test base_dirs              ... bench:       3,664 ns/iter (+/- 50)
test project_dirs           ... bench:       5,036 ns/iter (+/- 136)
test project_dirs_from_path ... bench:       4,008 ns/iter (+/- 31)
test user_dirs              ... bench:  56,280,472 ns/iter (+/- 6,954,712)
```

It might be worthwhile calling `cargo bench` on CI, just to make sure these continue to compile.

**Comment by soc** [comment]
On Linux?
I can totally believe that, sorting out the user dirs is pretty ugly, as – for whatever inscrutable reason – people didn't use env vars for them, but wrote a binary to read some random text file.

**Comment by soc** [comment]
@tbu- There are ideas of parsing the config file instead of shelling out to a process that calls the binary, but that is its own can of worms (not sure if env vars are allowed in there for instance...).

**Comment by soc** [comment]
Thanks!

**Pull request merged**
