### PR TITLE
Use dirs-rs instead of duplicating everything

### PR DESCRIPTION
**Pull request by aledomu**

### CODE REVIEW

**Comment by soc** [comment]
@aledomu Hi Alejandro, I considered doing this in the past, but shied away from doing it because I was concerned that this would cause version conflicts if a project's dependency used some version of `dirs` already, and the project (or its dependencies) used `directories`, which would also pull in `dirs` with this change.

What do you think about this?

> Why is this even testing against the compiler and standard library version of late 2016?

I'm using Rust 1.13 as a baseline, because I didn't feel that later versions added anything worthwhile to eat up the added language complexity.

I'm planning to reconsider this after the recent Rust module system changes have settled in for a bit.

**Comment by dwijnand** [comment]
> I was concerned that this would cause version conflicts if a project's dependency used some version of `dirs` already, and the project (or its dependencies) used `directories`, which would also pull in `dirs` with this change.

As long as dirs follows semver this shouldn't be an issue to the best of my knowledge. +116/-427 looks like a win.

**Comment by soc** [comment]
@dwijnand True, I guess I just preferred having no dependencies between them. I had some past experiments of moving the implementation in `dirs` and `directories` to some even more low-level crate and deduplicating things that way. Let's see whether I can dig this up again for comparison.

**Comment by dwijnand** [comment]
Talking about Rust version, I wonder if any of dirs or directories could be upgraded to be "const" functions, so they can be used in const definitions.  Just a thing I've noticed is happening in the pure parts of the stdlib, maybe not applicable here.

**Comment by soc** [comment]
@aledomu Thanks for the information!

**Comment by aledomu** [comment]
> Talking about Rust version, I wonder if any of dirs or directories could be upgraded to be "const" functions, so they can be used in const definitions. Just a thing I've noticed is happening in the pure parts of the stdlib, maybe not applicable here.

You can apply `const` only on the getters maybe and the trim function under `sys.rs`, but every function in `dirs-rs` depends on system global state at runtime, so it cannot be `const`. Pretty much everything here calls into hat library, so it doesn't apply here.

BTW I think it isn't stabilized yet.

**Comment by aledomu** [comment]
Is there anything else blocking this?

**Comment by soc** [comment]
Hey @aledomu,

I started deduplicating things in https://github.com/soc/directories-rs/commit/25d999269d9a556f9fe57bb72ae0d81a91313ee5 and credited you, I hope this is fine.

This is only the first sketch, as I'm integrating https://github.com/soc/directories-rs/pull/52 next, and will move more shared code to the new https://github.com/soc/dirs-sys-rs library.

Thanks!

**Comment by soc** [comment]
I'm closing this issue as I just published 2.0.0, which ships with the deduplication work.
Thanks to everyone involved!

**Pull request closed without merging**
